name: autoadd

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  scan_domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          git clone https://github.com/aboul3la/Sublist3r.git
          git clone https://github.com/thewhiteh4t/FinalRecon.git
          pip install -r Sublist3r/requirements.txt
          pip install -r FinalRecon/requirements.txt
          pip install anubis-netsec
          pip install --upgrade requests
          wget https://github.com/findomain/findomain/releases/latest/download/findomain-linux.zip
          unzip findomain-linux.zip
          sudo mv findomain /usr/local/bin/
          wget https://raw.githubusercontent.com/bebasid/bebasid/master/dev/scripts/scan.py
          echo "INSTALLATION DONE - ALL SET"

      - name: Set domain variable
        run: echo "domain=$(cat choppingblock.txt)" >> $GITHUB_ENV

      - name: Grant execute permission
        run: chmod +x /usr/local/bin/findomain

      - name: Subdomain Finder 1 | Sublist3r
        run: python Sublist3r/sublist3r.py -d $domain -o domain1

      - name: Subdomain Finder 2 | Findomain
        run: findomain -u domain2 -t $domain

      - name: Subdomain Finder 3 | Anubis
        run: anubis -t $domain -o domain3d && tail -n +22 domain3d > domain3 && rm domain3d

      - name: Subdomain Finder 4 | FinalRecon
        run: python FinalRecon/finalrecon.py --sub https://$domain > domain4d && tail -n +40 domain4d > domain4 && rm domain4d

      - name: Add domain lists to file
        run: |
          cat domain1 domain2 domain3 domain4 >> domains-unsorted.txt
          sort -u domains-unsorted.txt > domains-sorted.txt
          cat domains-sorted.txt

      - name: Run Scan
        run: |
          python scan.py domains-sorted.txt
          echo
          echo "Result Lists:"
          cat hosts-domains-sorted.txt

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin "https://${{ secrets.GH_TOKEN }}@github.com/mefinity/bebasin-sendiri.git"
          git add hosts-domains-sorted.txt
          git commit -m "Auto Bebasin"
          git push origin main